title: Ministerio de Educación de la provincia de La Rioja
baseurl: /
permalink: '/:title/'
layout_style: overflow
palette: orange
header:
  title: MINISTERIO DE EDUCACIÓN
  tagline: '#QuedateEnCasa'
  profile_img: /images/me.jpg
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; All rights reserved.'
  links:
    - text: Gobierno de La Rioja
      url: 'https://www.larioja.gov.ar/'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: '/posts/:title/'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
